local Plug = vim.fn['plug#']
vim.call('plug#begin', '~/.config/nvim/plugged')
Plug( 'junegunn/fzf', { ['do'] = vim.fn['fzf#install'] } )
Plug( 'junegunn/fzf.vim')
Plug( 'mbbill/undotree')
Plug( 'lervag/vimtex')
Plug( 'neovimhaskell/haskell-vim' )
Plug( 'neovim/nvim-lspconfig' )
Plug( 'hrsh7th/cmp-nvim-lsp')
Plug( 'hrsh7th/cmp-buffer')
Plug( 'hrsh7th/cmp-path')
Plug( 'hrsh7th/cmp-cmdline')
Plug( 'hrsh7th/nvim-cmp')
Plug( 'hrsh7th/cmp-vsnip')
Plug( 'hrsh7th/vim-vsnip')
Plug( 'rafamadriz/friendly-snippets' )
Plug( 'vim-airline/vim-airline' )
Plug( 'vim-airline/vim-airline-themes' )
Plug( 'nvim-lua/plenary.nvim' )
Plug( 'lewis6991/gitsigns.nvim' )
vim.call('plug#end')

vim.cmd([[
	source ~/.config/nvim/lua/keymappings.vim
	source ~/.config/nvim/lua/settings.vim
]])
require('nvim-lspconfig')
require('nvim-cmp')
require('vsnip')
require('gitsigns').setup()
